export const EMOJI_LIST = [
  { char: "😀", name: "smile" },
  { char: "😃", name: "happy" },
  { char: "😄", name: "grin" },
  { char: "😁", name: "laugh" },
  { char: "😆", name: "haha" },
  { char: "😅", name: "sweat_smile" },
  { char: "😂", name: "joy" },
  { char: "🤣", name: "rofl" },
  { char: "😊", name: "blush" },
  { char: "😇", name: "angel" },
  { char: "🙂", name: "slight_smile" },
  { char: "🙃", name: "upside_down" },
  { char: "😉", name: "wink" },
  { char: "😌", name: "relieved" },
  { char: "😍", name: "heart_eyes" },
  { char: "🥰", name: "smiling_face_with_hearts" },
  { char: "😘", name: "kissing_heart" },
  { char: "😗", name: "kissing" },
  { char: "😙", name: "kissing_smiling_eyes" },
  { char: "😚", name: "kissing_closed_eyes" },
  { char: "😋", name: "yum" },
  { char: "😛", name: "stuck_out_tongue" },
  { char: "😜", name: "stuck_out_tongue_wink_eye" },
  { char: "😝", name: "stuck_out_tongue_closed_eyes" },
  { char: "🤪", name: "zany" },
  { char: "🤨", name: "raised_eyebrow" },
  { char: "🧐", name: "monocle" },
  { char: "🤓", name: "nerd" },
  { char: "😎", name: "cool" },
  { char: "🤩", name: "star_eyes" },
  { char: "🥳", name: "party" },
  { char: "😏", name: "smirk" },
  { char: "😒", name: "unamused" },
  { char: "😞", name: "disappointed" },
  { char: "😔", name: "pensive" },
  { char: "😟", name: "worried" },
  { char: "😕", name: "confused" },
  { char: "🙁", name: "slight_frown" },
  { char: "☹️", name: "frown" },
  { char: "😣", name: "persevere" },
  { char: "😖", name: "confounded" },
  { char: "😫", name: "tired" },
  { char: "😩", name: "weary" },
  { char: "🥺", name: "pleading" },
  { char: "😢", name: "cry" },
  { char: "😭", name: "sob" },
  { char: "😤", name: "triumph" },
  { char: "😠", name: "angry" },
  { char: "😡", name: "rage" },
  { char: "🤬", name: "cursing" },
  { char: "🤯", name: "mind_blown" },
  { char: "😳", name: "flushed" },
  { char: "🥵", name: "hot" },
  { char: "🥶", name: "cold" },
  { char: "😱", name: "scream" },
  { char: "😨", name: "fearful" },
  { char: "😰", name: "cold_sweat" },
  { char: "😥", name: "sad_sweat" },
  { char: "😓", name: "sweat" },
  { char: "🤗", name: "hugs" },
  { char: "🤔", name: "thinking" },
  { char: "🤭", name: "shush" },
  { char: "🤫", name: "silent" },
  { char: "🤥", name: "liar" },
  { char: "😶", name: "no_mouth" },
  { char: "😐", name: "neutral" },
  { char: "😑", name: "expressionless" },
  { char: "😬", name: "grimacing" },
  { char: "🙄", name: "roll_eyes" },
  { char: "😯", name: "hushed" },
  { char: "😦", name: "frowning" },
  { char: "😧", name: "anguished" },
  { char: "😮", name: "open_mouth" },
  { char: "😲", name: "astonished" },
  { char: "🥱", name: "yawn" },
  { char: "😴", name: "sleepy" },
  { char: "🤤", name: "drool" },
  { char: "😪", name: "sleepy_face" },
  { char: "😵", name: "dizzy" },
  { char: "🤐", name: "zipped_mouth" },
  { char: "🥴", name: "woozy" },
  { char: "🤢", name: "nauseated" },
  { char: "🤮", name: "vomit" },
  { char: "🤧", name: "sneeze" },
  { char: "😷", name: "mask" },
  { char: "🤒", name: "fever" },
  { char: "🤕", name: "bandage" },
  { char: "🤑", name: "money_mouth" },
  { char: "🤠", name: "cowboy" },
  { char: "😈", name: "smiling_imp" },
  { char: "👿", name: "imp" },
  { char: "👹", name: "ogre" },
  { char: "👺", name: "goblin" },
  { char: "🤡", name: "clown" },
  { char: "💩", name: "poop" },
  { char: "👻", name: "ghost" },
  { char: "💀", name: "skull" },
  { char: "☠️", name: "skull_and_crossbones" },
  { char: "👽", name: "alien" },
  { char: "👾", name: "space_invader" },
  { char: "🤖", name: "robot" },
  { char: "🎃", name: "jack_o_lantern" },
  { char: "🔥", name: "fire" },
  { char: "✨", name: "sparkles" },
  { char: "✅", name: "check" },
  { char: "🎮", name: "gaming" },
  { char: "⚔️", name: "swords" },
  { char: "🛡️", name: "shield" },
  { char: "💎", name: "diamond" },
  { char: "🚀", name: "rocket" },
  { char: "❤️", name: "heart" },
  { char: "👍", name: "thumbsup" },
  { char: "👎", name: "thumbsdown" },
  { char: "👑", name: "crown" },
  { char: "🎯", name: "target" },
  { char: "🏆", name: "trophy" },
  { char: "👾", name: "alien_monster" },
  { char: "🐲", name: "dragon" },
  { char: "🐉", name: "dragon_full" },
  { char: "🐺", name: "wolf" },
  { char: "🦁", name: "lion" },
  { char: "🐯", name: "tiger" },
  { char: "💻", name: "computer" },
  { char: "⌨️", name: "keyboard" },
  { char: "⚔️", name: "combat" },
  { char: "🏹", name: "archery" },
  { char: "🗡️", name: "dagger" },
  { char: "🪓", name: "axe" },
  { char: "💣", name: "bomb" },
  { char: "🧨", name: "cracker" },
];

const EMOJI_SPANISH_LABELS: Record<string, string> = {
  smile: "sonrisa",
  happy: "feliz",
  grin: "risa",
  laugh: "carcajada",
  sweat_smile: "sonrisa nerviosa",
  joy: "alegría",
  rofl: "muerto de risa",
  blush: "sonrojo",
  angel: "ángel",
  wink: "guiño",
  heart_eyes: "ojos de corazón",
  smiling_face_with_hearts: "enamorado",
  cool: "genial",
  party: "fiesta",
  disappointed: "decepcionado",
  pensive: "pensativo",
  worried: "preocupado",
  confused: "confundido",
  frown: "ceño fruncido",
  cry: "llorar",
  sob: "sollozo",
  angry: "enfadado",
  rage: "furia",
  fire: "llamita",
  sparkles: "destellos",
  check: "verificado",
  gaming: "gaming",
  swords: "espadas",
  shield: "escudo",
  diamond: "diamante",
  rocket: "cohete",
  heart: "corazón",
  thumbsup: "pulgar arriba",
  thumbsdown: "pulgar abajo",
  crown: "corona",
  target: "objetivo",
  trophy: "trofeo",
  dragon: "dragón",
  wolf: "lobo",
  lion: "león",
  tiger: "tigre",
  computer: "ordenador",
  keyboard: "teclado",
  combat: "combate",
  archery: "arquería",
  dagger: "daga",
  axe: "hacha",
  bomb: "bomba",
  cracker: "petardo",
};

const EMOJI_SPANISH_ALIASES: Record<string, string[]> = {
  fire: ["fuego", "llama", "llamita"],
  sparkles: ["destellos", "brillos"],
  check: ["ok", "correcto", "verificado"],
  gaming: ["juego", "videojuego"],
  swords: ["espadas", "armas"],
  shield: ["escudo", "protección"],
  heart: ["amor", "corazón"],
  thumbsup: ["me gusta", "pulgar arriba"],
  thumbsdown: ["no me gusta", "pulgar abajo"],
  crown: ["rey", "reina", "corona"],
  target: ["objetivo", "meta"],
  trophy: ["trofeo", "victoria"],
  dragon: ["dragón"],
  wolf: ["lobo"],
  lion: ["león"],
  tiger: ["tigre"],
  computer: ["ordenador", "pc"],
  keyboard: ["teclado"],
  combat: ["combate", "pelea"],
  archery: ["arquería", "arco"],
  dagger: ["daga", "cuchillo"],
  axe: ["hacha"],
  bomb: ["bomba"],
  cracker: ["petardo", "explosivo"],
};

export const getEmojiDisplayName = (name: string) =>
  EMOJI_SPANISH_LABELS[name] || name.replace(/[_-]+/g, " ");

export const getEmojiSearchTerms = (name: string) => [
  name,
  ...(EMOJI_SPANISH_ALIASES[name] || []),
  getEmojiDisplayName(name),
];
