import { NextResponse } from 'next/server';
import { sb } from '@/infrastructure/auth/auth-options';

export type AbilityCategory =
  | 'Major DPS CD'
  | 'Minor DPS CD'
  | 'Major Heal CD'
  | 'Minor Heal CD'
  | 'Immunities'
  | 'Defensives'
  | 'Group DR'
  | 'Group Mobility'
  | 'Mobility'
  | 'Externals'
  | 'Utility'
  | 'externals';

export interface CooldownDefinition {
  spell_id: number;
  name: string;
  icon: string;
  duration: number;
  class_id: number;
  ability_type: 'PERSONAL' | 'EXTERNAL' | 'RAID' | 'UTILITY';
  allowed_specs: number[] | null;
  color: string;
  category: AbilityCategory | string;
  active_duration: number;
}

export const SEED_COOLDOWNS: Omit<
  CooldownDefinition,
  'id' | 'created_at' | 'updated_at'
>[] = [
    {
      spell_id: 97462,
      name: 'Berrido de convocación',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_warrior_rallyingcry.jpg',
      duration: 180,
      class_id: 1,
      ability_type: 'RAID',
      allowed_specs: null,
      color: '#C69B6D',
      category: 'Group DR',
      active_duration: 10,
    },
    {
      spell_id: 152277,
      name: 'Devastador',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/warrior_talent_icon_ravager.jpg',
      duration: 90,
      class_id: 1,
      ability_type: 'PERSONAL',
      allowed_specs: [71, 73],
      color: '#C69B6D',
      category: 'Major DPS CD',
      active_duration: 12,
    },
    {
      spell_id: 64382,
      name: 'Lanzamiento destrozador',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_warrior_shatteringthrow.jpg',
      duration: 180,
      class_id: 1,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#C69B6D',
      category: 'Utility',
      active_duration: 1,
    },
    {
      spell_id: 23920,
      name: 'Reflejo de hechizos',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_warrior_shieldreflection.jpg',
      duration: 25,
      class_id: 1,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#C69B6D',
      category: 'Defensives',
      active_duration: 5,
    },
    {
      spell_id: 118038,
      name: 'Muerte a espada',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_warrior_challange.jpg',
      duration: 180,
      class_id: 1,
      ability_type: 'PERSONAL',
      allowed_specs: [71],
      color: '#C69B6D',
      category: 'Defensives',
      active_duration: 8,
    },
    {
      spell_id: 871,
      name: 'Muro de escudo',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_warrior_shieldwall.jpg',
      duration: 240,
      class_id: 1,
      ability_type: 'PERSONAL',
      allowed_specs: [73],
      color: '#C69B6D',
      category: 'Defensives',
      active_duration: 8,
    },
    {
      spell_id: 184364,
      name: 'Regeneración enfurecida',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_warrior_focusedrage.jpg',
      duration: 120,
      class_id: 1,
      ability_type: 'PERSONAL',
      allowed_specs: [72],
      color: '#C69B6D',
      category: 'Defensives',
      active_duration: 8,
    },
    {
      spell_id: 228920,
      name: 'Devastador',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/warrior_talent_icon_ravager.jpg',
      duration: 90,
      class_id: 1,
      ability_type: 'PERSONAL',
      allowed_specs: [71, 72],
      color: '#C69B6D',
      category: 'Major DPS CD',
      active_duration: 6,
    },
    {
      spell_id: 107574,
      name: 'Avatar',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/warrior_talent_icon_avatar.jpg',
      duration: 90,
      class_id: 1,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#C69B6D',
      category: 'Major DPS CD',
      active_duration: 20,
    },
    {
      spell_id: 376079,
      name: "Champion's Spear",
      icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_ability_warrior_championsspear.jpg',
      duration: 90,
      class_id: 1,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#C69B6D',
      category: 'Major DPS CD',
      active_duration: 8,
    },
    {
      spell_id: 1719,
      name: 'Temeridad',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/warrior_talent_icon_innerrage.jpg',
      duration: 90,
      class_id: 1,
      ability_type: 'PERSONAL',
      allowed_specs: [72],
      color: '#C69B6D',
      category: 'Major DPS CD',
      active_duration: 12,
    },
    {
      spell_id: 304971,
      name: 'Estrago divino',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_bastion_paladin.jpg',
      duration: 60,
      class_id: 2,
      ability_type: 'RAID',
      allowed_specs: null,
      color: '#F58CBA',
      category: 'minor_heal',
      active_duration: 1,
    },
    {
      spell_id: 31884,
      name: 'Cólera vengativa',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_avenginewrath.jpg',
      duration: 120,
      class_id: 2,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#F58CBA',
      category: 'minor_heal',
      active_duration: 20,
    },
    {
      spell_id: 31821,
      name: 'Maestría de aura',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_auramastery.jpg',
      duration: 180,
      class_id: 2,
      ability_type: 'RAID',
      allowed_specs: [65],
      color: '#F58CBA',
      category: 'major_heal',
      active_duration: 8,
    },
    {
      spell_id: 6940,
      name: 'Bendición de sacrificio',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_sealofsacrifice.jpg',
      duration: 120,
      class_id: 2,
      ability_type: 'EXTERNAL',
      allowed_specs: null,
      color: '#F58CBA',
      category: 'external',
      active_duration: 12,
    },
    {
      spell_id: 216331,
      name: 'Cruzado vengativo',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_paladin_veneration.jpg',
      duration: 60,
      class_id: 2,
      ability_type: 'PERSONAL',
      allowed_specs: [65],
      color: '#F58CBA',
      category: 'minor_heal',
      active_duration: 12,
    },
    {
      spell_id: 642,
      name: 'Escudo divino',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_divineshield.jpg',
      duration: 300,
      class_id: 2,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#F58CBA',
      category: 'immunity',
      active_duration: 8,
    },
    {
      spell_id: 1022,
      name: 'Bendición de protección',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_sealofprotection.jpg',
      duration: 300,
      class_id: 2,
      ability_type: 'EXTERNAL',
      allowed_specs: null,
      color: '#F58CBA',
      category: 'immunity',
      active_duration: 10,
    },
    {
      spell_id: 633,
      name: 'Imposición de manos',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_layonhands.jpg',
      duration: 420,
      class_id: 2,
      ability_type: 'EXTERNAL',
      allowed_specs: null,
      color: '#F58CBA',
      category: 'external',
      active_duration: 1,
    },
    {
      spell_id: 204018,
      name: 'Bendición de resguardo contra hechizos',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_blessingofprotection.jpg',
      duration: 180,
      class_id: 2,
      ability_type: 'EXTERNAL',
      allowed_specs: null,
      color: '#F58CBA',
      category: 'external',
      active_duration: 10,
    },
    {
      spell_id: 498,
      name: 'Protección divina',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_divineprotection.jpg',
      duration: 60,
      class_id: 2,
      ability_type: 'PERSONAL',
      allowed_specs: [65, 70],
      color: '#F58CBA',
      category: 'defensive',
      active_duration: 8,
    },
    {
      spell_id: 109304,
      name: 'Excitación',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_hunter_onewithnature.jpg',
      duration: 120,
      class_id: 3,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#AAD372',
      category: 'minor_heal',
      active_duration: 1,
    },
    {
      spell_id: 186265,
      name: 'Aspecto de la tortuga',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_hunter_pet_turtle.jpg',
      duration: 180,
      class_id: 3,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#AAD372',
      category: 'immunity',
      active_duration: 8,
    },
    {
      spell_id: 190925,
      name: 'Arpón',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_hunter_harpoon.jpg',
      duration: 30,
      class_id: 3,
      ability_type: 'UTILITY',
      allowed_specs: [255],
      color: '#AAD372',
      category: 'mobility',
      active_duration: 1,
    },
    {
      spell_id: 264735,
      name: 'Supervivencia del más fuerte',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_spiritarmor.jpg',
      duration: 180,
      class_id: 3,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#AAD372',
      category: 'defensive',
      active_duration: 6,
    },
    {
      spell_id: 53480,
      name: 'Rugido de sacrificio',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_hunter_fervor.jpg',
      duration: 60,
      class_id: 3,
      ability_type: 'EXTERNAL',
      allowed_specs: [253, 255],
      color: '#AAD372',
      category: 'external',
      active_duration: 12,
    },
    {
      spell_id: 186257,
      name: 'Aspecto del guepardo',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_mount_jungletiger.jpg',
      duration: 180,
      class_id: 3,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#AAD372',
      category: 'mobility',
      active_duration: 5,
    },
    {
      spell_id: 1966,
      name: 'Amago',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_rogue_feint.jpg',
      duration: 15,
      class_id: 4,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#FFF468',
      category: 'defensive',
      active_duration: 6,
    },
    {
      spell_id: 315366,
      name: 'Embozo de encubrimiento',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_rogue_shroudofconcealment.jpg',
      duration: 360,
      class_id: 4,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#FFF468',
      category: 'utility',
      active_duration: 15,
    },
    {
      spell_id: 31230,
      name: 'Burlar a la muerte',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_rogue_cheatdeath.jpg',
      duration: 360,
      class_id: 4,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#FFF468',
      category: 'immunity',
      active_duration: 3,
    },
    {
      spell_id: 228260,
      name: 'Forma del Vacío',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_priest_void-blast.jpg',
      duration: 120,
      class_id: 5,
      ability_type: 'PERSONAL',
      allowed_specs: [258],
      color: '#FFFFFF',
      category: 'Major DPS CD',
      active_duration: 15,
    },
    {
      spell_id: 19236,
      name: 'Rezo desesperado',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_testoffaith.jpg',
      duration: 90,
      class_id: 5,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#FFFFFF',
      category: 'Defensives',
      active_duration: 10,
    },
    {
      spell_id: 62618,
      name: 'Palabra de poder: barrera',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_powerwordbarrier.jpg',
      duration: 180,
      class_id: 5,
      ability_type: 'RAID',
      allowed_specs: [256],
      color: '#FFFFFF',
      category: 'Group DR',
      active_duration: 10,
    },
    {
      spell_id: 64843,
      name: 'Himno divino',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_divinehymn.jpg',
      duration: 180,
      class_id: 5,
      ability_type: 'RAID',
      allowed_specs: [257],
      color: '#FFFFFF',
      category: 'Major Heal CD',
      active_duration: 8,
    },
    {
      spell_id: 10060,
      name: 'Infusión de poder',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_powerinfusion.jpg',
      duration: 120,
      class_id: 5,
      ability_type: 'EXTERNAL',
      allowed_specs: null,
      color: '#FFFFFF',
      category: 'Utility',
      active_duration: 20,
    },
    {
      spell_id: 200183,
      name: 'Apoteosis',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_priest_ascension.jpg',
      duration: 120,
      class_id: 5,
      ability_type: 'PERSONAL',
      allowed_specs: [257],
      color: '#FFFFFF',
      category: 'Major Heal CD',
      active_duration: 20,
    },
    {
      spell_id: 421453,
      name: 'Penitencia definitiva',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_priest_ascendance.jpg',
      duration: 240,
      class_id: 5,
      ability_type: 'RAID',
      allowed_specs: [256],
      color: '#FFFFFF',
      category: 'Major Heal CD',
      active_duration: 12,
    },
    {
      spell_id: 120517,
      name: 'Halo',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_priest_halo.jpg',
      duration: 40,
      class_id: 5,
      ability_type: 'RAID',
      allowed_specs: null,
      color: '#FFFFFF',
      category: 'Minor Heal CD',
      active_duration: 1,
    },
    {
      spell_id: 64901,
      name: 'Símbolo de esperanza',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_symbolofhope.jpg',
      duration: 180,
      class_id: 5,
      ability_type: 'RAID',
      allowed_specs: [257],
      color: '#FFFFFF',
      category: 'Utility',
      active_duration: 4,
    },
    {
      spell_id: 47788,
      name: 'Espíritu guardián',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_guardianspirit.jpg',
      duration: 180,
      class_id: 5,
      ability_type: 'EXTERNAL',
      allowed_specs: [257],
      color: '#FFFFFF',
      category: 'Externals',
      active_duration: 10,
    },
    {
      spell_id: 47585,
      name: 'Dispersión',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_dispersion.jpg',
      duration: 90,
      class_id: 5,
      ability_type: 'PERSONAL',
      allowed_specs: [258],
      color: '#FFFFFF',
      category: 'Defensives',
      active_duration: 6,
    },
    {
      spell_id: 33206,
      name: 'Supresión de dolor',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_painsupression.jpg',
      duration: 180,
      class_id: 5,
      ability_type: 'EXTERNAL',
      allowed_specs: [256],
      color: '#FFFFFF',
      category: 'Externals',
      active_duration: 8,
    },
    {
      spell_id: 246287,
      name: 'Evangelismo',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_divineillumination.jpg',
      duration: 90,
      class_id: 5,
      ability_type: 'RAID',
      allowed_specs: [256],
      color: '#FFFFFF',
      category: 'Minor Heal CD',
      active_duration: 6,
    },
    {
      spell_id: 212552,
      name: 'Paso espectral',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_helm_plate_raiddeathknight_p_01.jpg',
      duration: 60,
      class_id: 6,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#C41E3A',
      category: 'Mobility',
      active_duration: 4,
    },
    {
      spell_id: 48265,
      name: "Death's Advance",
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_demonicempathy.jpg',
      duration: 45,
      class_id: 6,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#C41E3A',
      category: 'Mobility',
      active_duration: 8,
    },
    {
      spell_id: 51271,
      name: 'Pilar de Escarcha',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_deathknight_pillaroffrost.jpg',
      duration: 45,
      class_id: 6,
      ability_type: 'PERSONAL',
      allowed_specs: [251],
      color: '#C41E3A',
      category: 'Minor DPS CD',
      active_duration: 12,
    },
    {
      spell_id: 49039,
      name: 'Exánime nato',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_raisedead.jpg',
      duration: 120,
      class_id: 6,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#C41E3A',
      category: 'Defensives',
      active_duration: 10,
    },
    {
      spell_id: 42650,
      name: 'Ejército de muertos',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_deathknight_armyofthedead.jpg',
      duration: 180,
      class_id: 6,
      ability_type: 'PERSONAL',
      allowed_specs: [252],
      color: '#C41E3A',
      category: 'Major DPS CD',
      active_duration: 30,
    },
    {
      spell_id: 152279,
      name: 'Aliento de Sindragosa',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_deathknight_breathofsindragosa.jpg',
      duration: 120,
      class_id: 6,
      ability_type: 'PERSONAL',
      allowed_specs: [251],
      color: '#C41E3A',
      category: 'Major DPS CD',
      active_duration: 20,
    },
    {
      spell_id: 444347,
      name: 'Carga de la muerte',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_demonicempathy.jpg',
      duration: 45,
      class_id: 6,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#C41E3A',
      category: 'Mobility',
      active_duration: 10,
    },
    {
      spell_id: 51052,
      name: 'Zona antimagia',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_deathknight_antimagiczone.jpg',
      duration: 120,
      class_id: 6,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#C41E3A',
      category: 'Group DR',
      active_duration: 10,
    },
    {
      spell_id: 48792,
      name: 'Entereza ligada al hielo',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_deathknight_iceboundfortitude.jpg',
      duration: 180,
      class_id: 6,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#C41E3A',
      category: 'Defensives',
      active_duration: 8,
    },
    {
      spell_id: 46585,
      name: 'Levantar muerto',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_pet_ghoul.jpg',
      duration: 120,
      class_id: 6,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#C41E3A',
      category: 'Minor DPS CD',
      active_duration: 60,
    },
    {
      spell_id: 190778,
      name: "Frostwyrm's Fury",
      icon: 'https://wow.zamimg.com/images/wow/icons/large/achievement_boss_sindragosa.jpg',
      duration: 180,
      class_id: 6,
      ability_type: 'PERSONAL',
      allowed_specs: [251],
      color: '#C41E3A',
      category: 'Major DPS CD',
      active_duration: 1,
    },
    {
      spell_id: 48707,
      name: 'Caparazón antimagia',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_antimagicshell.jpg',
      duration: 60,
      class_id: 6,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#C41E3A',
      category: 'Defensives',
      active_duration: 5,
    },
    {
      spell_id: 191634,
      name: 'Guardia de la Tormenta',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_thunderking_lightningwhip.jpg',
      duration: 60,
      class_id: 7,
      ability_type: 'PERSONAL',
      allowed_specs: [262, 264],
      color: '#0070DE',
      category: 'Minor DPS CD',
      active_duration: 15,
    },
    {
      spell_id: 79206,
      name: 'Gracia del caminaespíritus',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_spiritwalkersgrace.jpg',
      duration: 120,
      class_id: 7,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#0070DE',
      category: 'Utility',
      active_duration: 15,
    },
    {
      spell_id: 98008,
      name: 'Tótem Enlace de espíritu',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_spiritlink.jpg',
      duration: 180,
      class_id: 7,
      ability_type: 'RAID',
      allowed_specs: [264],
      color: '#0070DE',
      category: 'Group DR',
      active_duration: 6,
    },
    {
      spell_id: 384352,
      name: 'Vientos de fatalidad',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_ironmaidens_swirlingvortex.jpg',
      duration: 90,
      class_id: 7,
      ability_type: 'PERSONAL',
      allowed_specs: [263],
      color: '#0070DE',
      category: 'Minor DPS CD',
      active_duration: 8,
    },
    {
      spell_id: 114050,
      name: 'Ascensión',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_fire_elementaldevastation.jpg',
      duration: 180,
      class_id: 7,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#0070DE',
      category: 'Major DPS CD',
      active_duration: 15,
    },
    {
      spell_id: 108280,
      name: 'Tótem de Marea de sanación',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_healingtide.jpg',
      duration: 180,
      class_id: 7,
      ability_type: 'RAID',
      allowed_specs: [264],
      color: '#0070DE',
      category: 'Major Heal CD',
      active_duration: 10,
    },
    {
      spell_id: 192077,
      name: 'Tótem de Carga de viento',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_windwalktotem.jpg',
      duration: 120,
      class_id: 7,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#0070DE',
      category: 'group_mobility',
      active_duration: 15,
    },
    {
      spell_id: 108271,
      name: 'Cambio astral',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_astralshift.jpg',
      duration: 90,
      class_id: 7,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#0070DE',
      category: 'Defensives',
      active_duration: 12,
    },
    {
      spell_id: 207399,
      name: 'Tótem de Protección ancestral',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_reincarnation.jpg',
      duration: 300,
      class_id: 7,
      ability_type: 'RAID',
      allowed_specs: [264],
      color: '#0070DE',
      category: 'Major Heal CD',
      active_duration: 30,
    },
    {
      spell_id: 443448,
      name: 'Capacidad primordial',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_monk_chiswirl.jpg',
      duration: 24,
      class_id: 7,
      ability_type: 'PERSONAL',
      allowed_specs: [263],
      color: '#0070DE',
      category: 'Minor DPS CD',
      active_duration: 20,
    },
    {
      spell_id: 198103,
      name: 'Elemental de Tierra',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_earthelemental_totem.jpg',
      duration: 300,
      class_id: 7,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#0070DE',
      category: 'Defensives',
      active_duration: 60,
    },
    {
      spell_id: 45438,
      name: 'Bloque de hielo',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_frost_frost.jpg',
      duration: 240,
      class_id: 8,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#3FC7EB',
      category: 'immunity',
      active_duration: 10,
    },
    {
      spell_id: 333889,
      name: 'Dominación vil',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_felmending.jpg',
      duration: 180,
      class_id: 9,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#8788EE',
      category: 'Utility',
      active_duration: 1,
    },
    {
      spell_id: 108416,
      name: 'Pacto oscuro',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_deathpact.jpg',
      duration: 60,
      class_id: 9,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#8788EE',
      category: 'Defensives',
      active_duration: 20,
    },
    {
      spell_id: 442971,
      name: 'Malevolencia',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_warlock_demonicalsoul.jpg',
      duration: 60,
      class_id: 9,
      ability_type: 'PERSONAL',
      allowed_specs: [265],
      color: '#8788EE',
      category: 'Major DPS CD',
      active_duration: 20,
    },
    {
      spell_id: 104773,
      name: 'Resolución inagotable',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_demonictactics.jpg',
      duration: 180,
      class_id: 9,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#8788EE',
      category: 'Defensives',
      active_duration: 8,
    },
    {
      spell_id: 18540,
      name: 'Invocar guardia apocalíptico',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_summoninfernal.jpg',
      duration: 180,
      class_id: 9,
      ability_type: 'PERSONAL',
      allowed_specs: [266],
      color: '#8788EE',
      category: 'Major DPS CD',
      active_duration: 25,
    },
    {
      spell_id: 205180,
      name: 'Invocar miradaoscura',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_beholderwarlock.jpg',
      duration: 120,
      class_id: 9,
      ability_type: 'PERSONAL',
      allowed_specs: [265],
      color: '#8788EE',
      category: 'Major DPS CD',
      active_duration: 20,
    },
    {
      spell_id: 1122,
      name: 'Invocar infernal',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_summoninfernal.jpg',
      duration: 180,
      class_id: 9,
      ability_type: 'PERSONAL',
      allowed_specs: [267],
      color: '#8788EE',
      category: 'Major DPS CD',
      active_duration: 30,
    },
    {
      spell_id: 111771,
      name: 'Portal demoníaco',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_warlock_demonicportal_green.jpg',
      duration: 60,
      class_id: 9,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#8788EE',
      category: 'Group Mobility',
      active_duration: 1,
    },
    {
      spell_id: 442345,
      name: 'Grimorio: Devastador vil',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_summonfelhunter.jpg',
      duration: 120,
      class_id: 9,
      ability_type: 'PERSONAL',
      allowed_specs: [266],
      color: '#8788EE',
      category: 'Minor DPS CD',
      active_duration: 20,
    },
    {
      spell_id: 442145,
      name: 'Grimorio: Se�or de los diablillos',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_summonimp.jpg',
      duration: 120,
      class_id: 9,
      ability_type: 'PERSONAL',
      allowed_specs: [266],
      color: '#8788EE',
      category: 'Minor DPS CD',
      active_duration: 20,
    },
    {
      spell_id: 265187,
      name: 'Invocar tirano demoníaco',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_summondemonictyrant.jpg',
      duration: 90,
      class_id: 9,
      ability_type: 'PERSONAL',
      allowed_specs: [266],
      color: '#8788EE',
      category: 'Major DPS CD',
      active_duration: 15,
    },
    {
      spell_id: 443681,
      name: 'Cosecha oscura',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_warlock_harvestoflife.jpg',
      duration: 60,
      class_id: 9,
      ability_type: 'PERSONAL',
      allowed_specs: [265],
      color: '#8788EE',
      category: 'Minor DPS CD',
      active_duration: 3,
    },
    {
      spell_id: 116841,
      name: "Tiger's Lust",
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_monk_tigerslust.jpg',
      duration: 30,
      class_id: 10,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#00FF96',
      category: 'group_mobility',
      active_duration: 6,
    },
    {
      spell_id: 122278,
      name: 'Mitigar daño',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_monk_dampenharm.jpg',
      duration: 120,
      class_id: 10,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#00FF96',
      category: 'defensive',
      active_duration: 10,
    },
    {
      spell_id: 322118,
      name: "Invoke Yu'lon",
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_monk_dragonkick.jpg',
      duration: 180,
      class_id: 10,
      ability_type: 'RAID',
      allowed_specs: [270],
      color: '#00FF96',
      category: 'major_heal',
      active_duration: 25,
    },
    {
      spell_id: 115203,
      name: 'Brebaje reconstituyente',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_monk_fortifyingale_new.jpg',
      duration: 180,
      class_id: 10,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#00FF96',
      category: 'defensive',
      active_duration: 15,
    },
    {
      spell_id: 122783,
      name: 'Difuminar magia',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_monk_diffusemagic.jpg',
      duration: 90,
      class_id: 10,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#00FF96',
      category: 'defensive',
      active_duration: 6,
    },
    {
      spell_id: 116849,
      name: 'Crisálida vital',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_monk_chicocoon.jpg',
      duration: 120,
      class_id: 10,
      ability_type: 'EXTERNAL',
      allowed_specs: [270],
      color: '#00FF96',
      category: 'external',
      active_duration: 12,
    },
    {
      spell_id: 122470,
      name: 'Toque de karma',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_monk_touchofkarma.jpg',
      duration: 90,
      class_id: 10,
      ability_type: 'PERSONAL',
      allowed_specs: [269],
      color: '#00FF96',
      category: 'defensive',
      active_duration: 10,
    },
    {
      spell_id: 119996,
      name: 'Trascendencia',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/monk_ability_transcendence.jpg',
      duration: 45,
      class_id: 10,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#00FF96',
      category: 'mobility',
      active_duration: 1,
    },
    {
      spell_id: 115310,
      name: 'Reanimación',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_monk_revival.jpg',
      duration: 180,
      class_id: 10,
      ability_type: 'RAID',
      allowed_specs: [270],
      color: '#00FF96',
      category: 'major_heal',
      active_duration: 1,
    },
    {
      spell_id: 116844,
      name: 'Anillo de paz',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_monk_ringofpeace.jpg',
      duration: 45,
      class_id: 10,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#00FF96',
      category: 'utility',
      active_duration: 5,
    },
    {
      spell_id: 325197,
      name: 'Invocar a Chi-Ji, la Grulla Roja',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_pet_cranegod.jpg',
      duration: 180,
      class_id: 10,
      ability_type: 'RAID',
      allowed_specs: [270],
      color: '#00FF96',
      category: 'major_heal',
      active_duration: 25,
    },
    {
      spell_id: 102342,
      name: 'Corteza de hierro',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_druid_ironbark.jpg',
      duration: 90,
      class_id: 11,
      ability_type: 'EXTERNAL',
      allowed_specs: [105],
      color: '#FF7D0A',
      category: 'Externals',
      active_duration: 12,
    },
    {
      spell_id: 205636,
      name: 'Fuerza de la Naturaleza',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_forceofnature.jpg',
      duration: 60,
      class_id: 11,
      ability_type: 'UTILITY',
      allowed_specs: [102],
      color: '#FF7D0A',
      category: 'Minor DPS CD',
      active_duration: 10,
    },
    {
      spell_id: 102401,
      name: 'Carga salvaje',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_druid_wildcharge.jpg',
      duration: 15,
      class_id: 11,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#FF7D0A',
      category: 'Mobility',
      active_duration: 1,
    },
    {
      spell_id: 102560,
      name: 'Encarnación: Elegido de Elune',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_druid_incarnation.jpg',
      duration: 180,
      class_id: 11,
      ability_type: 'PERSONAL',
      allowed_specs: [102],
      color: '#FF7D0A',
      category: 'Major DPS CD',
      active_duration: 30,
    },
    {
      spell_id: 106898,
      name: 'Rugido de estampida',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_druid_stampedingroar_cat.jpg',
      duration: 120,
      class_id: 11,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#FF7D0A',
      category: 'Group Mobility',
      active_duration: 8,
    },
    {
      spell_id: 61336,
      name: 'Instintos de supervivencia',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_tigersroar.jpg',
      duration: 180,
      class_id: 11,
      ability_type: 'PERSONAL',
      allowed_specs: [103, 104],
      color: '#FF7D0A',
      category: 'Defensives',
      active_duration: 6,
    },
    {
      spell_id: 22812,
      name: 'Piel de corteza',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_stoneclawtotem.jpg',
      duration: 60,
      class_id: 11,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#FF7D0A',
      category: 'Defensives',
      active_duration: 12,
    },
    {
      spell_id: 380199,
      name: 'Alineación celestial',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_naturetouchgrow.jpg',
      duration: 180,
      class_id: 11,
      ability_type: 'PERSONAL',
      allowed_specs: [102],
      color: '#FF7D0A',
      category: 'Major DPS CD',
      active_duration: 20,
    },
    {
      spell_id: 202770,
      name: 'Furia de Elune',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_dreamstate.jpg',
      duration: 60,
      class_id: 11,
      ability_type: 'PERSONAL',
      allowed_specs: [102],
      color: '#FF7D0A',
      category: 'Minor DPS CD',
      active_duration: 8,
    },
    {
      spell_id: 33891,
      name: 'Encarnación: Árbol de vida',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_improvedtreeform.jpg',
      duration: 180,
      class_id: 11,
      ability_type: 'PERSONAL',
      allowed_specs: [105],
      color: '#FF7D0A',
      category: 'Major Heal CD',
      active_duration: 30,
    },
    {
      spell_id: 740,
      name: 'Tranquilidad',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_tranquility.jpg',
      duration: 180,
      class_id: 11,
      ability_type: 'RAID',
      allowed_specs: [105],
      color: '#FF7D0A',
      category: 'Major Heal CD',
      active_duration: 8,
    },
    {
      spell_id: 5487,
      name: 'Forma de oso',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_racial_bearform.jpg',
      duration: 0,
      class_id: 11,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#FF7D0A',
      category: 'Defensives',
      active_duration: 0,
    },
    {
      spell_id: 29166,
      name: 'Estimular',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_lightning.jpg',
      duration: 180,
      class_id: 11,
      ability_type: 'UTILITY',
      allowed_specs: [102, 105],
      color: '#FF7D0A',
      category: 'Utility',
      active_duration: 10,
    },
    {
      spell_id: 106951,
      name: 'Rabia',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_berserk.jpg',
      duration: 180,
      class_id: 11,
      ability_type: 'PERSONAL',
      allowed_specs: [103, 104],
      color: '#FF7D0A',
      category: 'Major DPS CD',
      active_duration: 20,
    },
    {
      spell_id: 391528,
      name: 'Convocar a los espíritus',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_ability_druid_convokethespirits.jpg',
      duration: 60,
      class_id: 11,
      ability_type: 'RAID',
      allowed_specs: [102, 103, 105],
      color: '#FF7D0A',
      category: 'Major DPS CD',
      active_duration: 4,
    },
    {
      spell_id: 192081,
      name: 'Pelaje férreo',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_ironfur.jpg',
      duration: 0,
      class_id: 11,
      ability_type: 'PERSONAL',
      allowed_specs: [103, 104],
      color: '#FF7D0A',
      category: 'Defensives',
      active_duration: 7,
    },
    {
      spell_id: 252216,
      name: 'Acometida de tigre',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_dash_orange.jpg',
      duration: 45,
      class_id: 11,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#FF7D0A',
      category: 'Mobility',
      active_duration: 5,
    },
    {
      spell_id: 203819,
      name: 'Púas demoníacas',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_demonhunter_demonspikes.jpg',
      duration: 20,
      class_id: 12,
      ability_type: 'PERSONAL',
      allowed_specs: [581],
      color: '#A330C9',
      category: 'Defensives',
      active_duration: 6,
    },
    {
      spell_id: 426217,
      name: 'Sello de inquina',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_demonhunter_sigilofmisery.jpg',
      duration: 120,
      class_id: 12,
      ability_type: 'PERSONAL',
      allowed_specs: [581],
      color: '#A330C9',
      category: 'Minor DPS CD',
      active_duration: 10,
    },
    {
      spell_id: 198793,
      name: 'Retirada vengativa',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_12_voiddh_ability_vengefulretreat.jpg',
      duration: 20,
      class_id: 12,
      ability_type: 'UTILITY',
      allowed_specs: [577],
      color: '#A330C9',
      category: 'Mobility',
      active_duration: 1,
    },
    {
      spell_id: 370965,
      name: 'La caza',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_ability_demonhunter_thehunt.jpg',
      duration: 90,
      class_id: 12,
      ability_type: 'PERSONAL',
      allowed_specs: [577],
      color: '#A330C9',
      category: 'Major DPS CD',
      active_duration: 1,
    },
    {
      spell_id: 202138,
      name: 'Sigilo de cadenas',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_demonhunter_sigilofchains.jpg',
      duration: 90,
      class_id: 12,
      ability_type: 'UTILITY',
      allowed_specs: [581],
      color: '#A330C9',
      category: 'Utility',
      active_duration: 6,
    },
    {
      spell_id: 204021,
      name: 'Marca ígnea',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_demonhunter_fierybrand.jpg',
      duration: 60,
      class_id: 12,
      ability_type: 'EXTERNAL',
      allowed_specs: [581],
      color: '#A330C9',
      category: 'Externals',
      active_duration: 8,
    },
    {
      spell_id: 207407,
      name: 'Trinchador de almas',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_glaive_1h_artifactaldrochi_d_01.jpg',
      duration: 60,
      class_id: 12,
      ability_type: 'PERSONAL',
      allowed_specs: [581],
      color: '#A330C9',
      category: 'Minor DPS CD',
      active_duration: 1,
    },
    {
      spell_id: 191427,
      name: 'Metamorfosis',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_demonhunter_metamorphasisdps.jpg',
      duration: 120,
      class_id: 12,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#A330C9',
      category: 'Major DPS CD',
      active_duration: 24,
    },
    {
      spell_id: 196718,
      name: 'Oscuridad',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_demonhunter_darkness.jpg',
      duration: 180,
      class_id: 12,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#A330C9',
      category: 'Group DR',
      active_duration: 8,
    },
    {
      spell_id: 198589,
      name: 'Disiparse',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_demonhunter_blur.jpg',
      duration: 60,
      class_id: 12,
      ability_type: 'PERSONAL',
      allowed_specs: [577],
      color: '#A330C9',
      category: 'Defensives',
      active_duration: 10,
    },
    {
      spell_id: 370665,
      name: 'Rescatar',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_evoker_flywithme.jpg',
      duration: 60,
      class_id: 13,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#33937F',
      category: 'Mobility',
      active_duration: 1,
    },
    {
      spell_id: 363534,
      name: 'Rebobinar',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_evoker_rewind.jpg',
      duration: 240,
      class_id: 13,
      ability_type: 'RAID',
      allowed_specs: [1468],
      color: '#33937F',
      category: 'Major Heal CD',
      active_duration: 1,
    },
    {
      spell_id: 370553,
      name: 'Inclinar la balanza',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_evoker_tipthescales.jpg',
      duration: 120,
      class_id: 13,
      ability_type: 'UTILITY',
      allowed_specs: null,
      color: '#33937F',
      category: 'Utility',
      active_duration: 1,
    },
    {
      spell_id: 374348,
      name: 'Llamarada de renovación',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_evoker_masterylifebinder_red.jpg',
      duration: 90,
      class_id: 13,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#33937F',
      category: 'Defensives',
      active_duration: 8,
    },
    {
      spell_id: 373861,
      name: 'Anomalía temporal',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_evoker_temporalanomaly.jpg',
      duration: 120,
      class_id: 13,
      ability_type: 'RAID',
      allowed_specs: [1468],
      color: '#33937F',
      category: 'Major Heal CD',
      active_duration: 2,
    },
    {
      spell_id: 363916,
      name: 'Escamas obsidiana',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_artifact_dragonscales.jpg',
      duration: 90,
      class_id: 13,
      ability_type: 'PERSONAL',
      allowed_specs: null,
      color: '#33937F',
      category: 'Defensives',
      active_duration: 12,
    },
    {
      spell_id: 370984,
      name: 'Comunión esmeralda',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_evoker_green_01.jpg',
      duration: 180,
      class_id: 13,
      ability_type: 'RAID',
      allowed_specs: [1468],
      color: '#33937F',
      category: 'Major Heal CD',
      active_duration: 5,
    },
    {
      spell_id: 370537,
      name: 'Estasis',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_evoker_stasis.jpg',
      duration: 90,
      class_id: 13,
      ability_type: 'PERSONAL',
      allowed_specs: [1468],
      color: '#33937F',
      category: 'Minor Heal CD',
      active_duration: 1,
    },
    {
      spell_id: 406732,
      name: 'Paradoja espacial',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_evoker_stretchtime.jpg',
      duration: 120,
      class_id: 13,
      ability_type: 'UTILITY',
      allowed_specs: [1468, 1473],
      color: '#33937F',
      category: 'Utility',
      active_duration: 10,
    },
    {
      spell_id: 374227,
      name: 'Céfiro',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_evoker_hoverblack.jpg',
      duration: 120,
      class_id: 13,
      ability_type: 'RAID',
      allowed_specs: null,
      color: '#33937F',
      category: 'Group DR',
      active_duration: 8,
    },
    {
      spell_id: 374968,
      name: 'Espiral temporal',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_evoker_timespiral.jpg',
      duration: 120,
      class_id: 13,
      ability_type: 'RAID',
      allowed_specs: null,
      color: '#33937F',
      category: 'Group Mobility',
      active_duration: 10,
    },
    {
      spell_id: 357170,
      name: 'Dilatación temporal',
      icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_evoker_timedilation.jpg',
      duration: 60,
      class_id: 13,
      ability_type: 'EXTERNAL',
      allowed_specs: [1468],
      color: '#33937F',
      category: 'Externals',
      active_duration: 8,
    },
  ];

export async function POST(req: Request) {
  try {
    const supabase = sb;

    // Clear existing
    const { error: deleteError } = await supabase
      .from('cooldown_definitions')
      .delete()
      .neq('id', 0);

    if (deleteError) throw deleteError;

    // Insert new
    const { error: insertError } = await supabase
      .from('cooldown_definitions')
      .insert(SEED_COOLDOWNS);

    if (insertError) throw insertError;

    return NextResponse.json({ success: true, count: SEED_COOLDOWNS.length });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function GET() {
  return NextResponse.json({ SEED_COOLDOWNS });
}
