// Auto-generated by scripts/generate-blur-placeholders.mjs
// Do not edit manually. Run prebuild to regenerate.

export const blurDataUrls = {
  logoTexto: "data:image/webp;base64,UklGRnAAAABXRUJQVlA4WAoAAAAQAAAACQAAAgAAQUxQSB8AAAAAP4UUAAAAAAAAAIe/iIh+iZ6pnWlQoDs0NywzMD4fAFZQOCAqAAAA8AEAnQEqCgADAAVAfCWMAnQBEBP5OmUwAP7aJ2Rz4Zoa0ck0XFjDXgAA",
  midnightCinematic: "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoKAAQABUB8JZACdAERCANXAsAA/iebMo8V3hBF0X6tPU7qLUE5AAAA",
  midnightBattle: "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAcABUB8JZQAAlAhqgD+2ab2TumQB8EZT2MmjCoB9YxcQACiNbAA",
  historiaCultura: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAABQAQCdASoKAAYABUB8JQBOgCgAAP7wB+z5Jf508OH3fCoAAAA=",
  recruitment: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACwAQCdASoKAAUABUB8JQBWACHfTjeAAP7ui5ml5HMQr5SAAAA=",
} as const;
